### ISSUE TITLE
Purpose?

### ISSUE THREAD

**Issue by jhs** [micnews/ldbcmp#3]
Hi, Paolo. This could be very useful for my work on level replication. One issue I am finding is that downtime can cause databases to diverge. Depending on the application usage, this could be a big problem. One solution is to handle it like Git: detect divergence, and allow a mechanism to merge databases back together, either with or without human involvement.

I guess my first question is, why C++ instead of doing it with LevelUp? Thanks!

**Comment by heapwolf** [comment]
Ah! That's why we're going to try level-replicator. It's designed to
be partition tolerant by expecting downtime.

On Sunday, May 18, 2014, Jason Smith notifications@github.com wrote:

> Hi, Paolo. This could be very useful for my work on level replication. One
> issue I am finding is that downtime can cause databases to diverge.
> Depending on the application usage, this could be a big problem. One
> solution is to handle it like Git: detect divergence, and allow a mechanism
> to merge databases back together, either with or without human involvement.
> 
> I guess my first question is, why C++ instead of doing it with LevelUp?
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/PolicyMic/ldbcmp/issues/3
> .

## 

## 

Paolo Fragomeni
Founder, Here is How
http://hereishow.to

github.com/hij1nx
twitter.com/hij1nx

**Comment by heapwolf** [comment]
done in c++ for performance
